name: app_environment
channels:
  - snowflake
dependencies:
  - langchain=0.3.25
  - langchain-text-splitters=0.3.8
  - numpy=2.2.5
  - openai=1.77.0
  - openpyxl=3.1.5
  - pandas=2.2.3
  - python=3.11.*
  - requests=2.32.3
  - snowflake-snowpark-python=
  - snowflake.core=1.7.0
  - streamlit=
  - tabulate=0.9.0
